# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a8af45e0d797cec5f59ad7ca9d07ef8d0d183f9b60a3dba335926715940632c5d06350cbfedf7a670c07e462a98aa065a613fb0a3006dcfdf46c344dde8d4c2

test:
  secret_key_base: bc4aa01543306398998b1eefac9d96c286b346319f8cb76a22d1c7097666362236ebb6c18cd37a505714941a71f4af899a88745682aaab90cd7889ab0025dd0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
